name: build
on: [push]
jobs:
  build:
    name: Run Specifications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
      - run: npm install
      - run: npm test
